### ISSUE TITLE
No option to exclude or obfuscate secrets within core-site.xml

### ISSUE THREAD

**Issue by nleaman** [rsvihladremio/dremio-diagnostic-collector#42]
core-site.xml can include `fs.s3a.secret.key` and `fs.s3a.access.key` values which is a security concern.

**Comment by markcurtis1970** [comment]
@nleaman - thanks for opening this. I propose we fix this by adding an exclude option top the command line

To implement this we would probably test for the file here https://github.com/rsvihladremio/dremio-diagnostic-collector/blob/main/collection/capture.go#L271-L278

Let me know what you think, since this would I believe be the cleanest option rather than directly modifying files, then if you're asked to supply that file then you can after applying your own obfuscation as needed

**Comment by markcurtis1970** [comment]
@nleaman I have pushed a new release v0.1.5 where you can exclude files - if this meets your needs then let us know.

**Comment by rsvihladremio** [comment]
we are going to stop collecting this soon
